# general settings
name: UHDM_IGAB_Sturcture_nopretrain-3losses
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: Enhancement/data_25/train/gt
    dataroot_lq: Enhancement/data_25/train/input/input
    dataroot_gt_s: Enhancement/data_25/train/gt_s
    dataroot_lq_s: Enhancement/data_25/train/input/input_s
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [1]             # Batch size per gpu
    iters: [60000]
    gt_size: 1600 # 1280  1600  # Max patch size for progressive training
    gt_sizes: [1600] # 320,448,448,640,640,1024]
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]
    # iters: [300000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: Enhancement/data_25/train/gt
    dataroot_lq: Enhancement/data_25/train/input/input
    dataroot_gt_s: Enhancement/data_25/train/gt_s
    dataroot_lq_s: Enhancement/data_25/train/input/input_s
    io_backend:
      type: disk

# network structures
network_g:
  type: UHDM

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  total_iter: 60000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [18400, 41600]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]  
  
  mixing_augs:
    mixup: true # false # true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: multi_VGGPerceptualLoss # multi_VGGPerceptualLoss  CharbonnierLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 5e6
  save_img: true
  rgb2bgr: true
  use_image: false
  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
